### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mBigFlower** [SpongeBobSun/mCalendarView#1]
I want to ask three days from my boss to be happy with my girlfriend . but the boss refuse me . 
What can I do ?

**Comment by SpongeBobSun** [comment]
I want to ask three days **off** from my boss to be happy with my girlfriend . but the boss refuse me .
What can I do ?
Do you mean this ?

**Comment by mBigFlower** [comment]
@SpongeBobSun  fuck. you win
