### ISSUE TITLE
Background Colors

### ISSUE THREAD

**Issue by jcaruso001** [SpongeBobSun/mCalendarView#12]
Can we set background colors on a day by day basis?

**Comment by SpongeBobSun** [comment]
What do you mean by day basis?

**Comment by jcaruso001** [comment]
I would want the 1st to have a red LEFTSIDEBAR and the 2nd to have a yellow LEFTSIDEBAR and the 3rdto have a brown LEFTSIDEBAR... and so on.

**Comment by SpongeBobSun** [comment]
Well.......currently we only have one mark style and it's a global style.
I'll modify my code and see if I can implement this or not.
Once done I'll let you know.
Thanks.

**Comment by jcaruso001** [comment]
That would be amazing, I love this calendar view and would love to put it in my app!

**Comment by SpongeBobSun** [comment]
Hi, I've fixed this issue. Please pull the latest code.
Now you can use different highlight style & color between highlighted dates.
