### ISSUE TITLE
Current Date Issue

### ISSUE THREAD

**Issue by jcaruso001** [SpongeBobSun/mCalendarView#14]
So I set up the project with the updated code. I'm looping through all the days and putting the appropriate color on that day... however, it keeps crashing. IMHO it looks as if the bug is assassinated with setting the the color on the current date.

I was able to test this by checking if the date I want to set the color for is today and skipping it... No crash.

To reproduce set up an expandable calendar view and attempt to set set the mark style to leftbar and a color...

Thanks!

**Comment by SpongeBobSun** [comment]
Hmmm...this looks like something went wrong in the exp calendar view. Could you send me some trace back from the android console? That my help me to locate the bug.
 :)
Thanks.

Bob.

Sent from my iPad

**Comment by SpongeBobSun** [comment]
Fixed. Please pull the latest commit and verify. Thanks.

**Comment by jcaruso001** [comment]
Thanks Bob, I haven't had time to reproduce it.

**Comment by SpongeBobSun** [comment]
You are welcome~

**Comment by SpongeBobSun** [comment]
BTW if you guys decide to use this lib, could you tell me which app are you building when you finished? I want to add your app name & link to my readme file. You know, just to show everybody this lib is `battlefield testified`.
:)
Thanks.

**Comment by jcaruso001** [comment]
Absolutely! I'm in the middle of a redesign of an app is currently on the market. I hope to have it out by the end of the month!

**Comment by SpongeBobSun** [comment]
Glad to hear that! Thanks! :+1: :+1: :+1: :+1:
