### ISSUE TITLE
Mark Dates in ExpCalendarView? (Clarification)

### ISSUE THREAD

**Issue by Praveen2106** [SpongeBobSun/mCalendarView#16]
Hi,
Is it possible to mark dates in ExpCalendarView?

**Comment by SpongeBobSun** [comment]
Sure it is.
You can use below two methods to mark a date in both MCalendarView & ExpCalendarView.

``` java
        expCalendarView.markDate(2016, 3, 16);
        expCalendarView.markDate(new DateData(2016, 3, 20).setMarkStyle(new MarkStyle(MarkStyle.DOT, Color.GREEN)));
```

Please read my doc for more information.
If you like this lib, start it please :)

Thanks.
Bob.

**Comment by Praveen2106** [comment]
Thanks Bob!
