### ISSUE TITLE
Clear ExpCalendarView

### ISSUE THREAD

**Issue by jcaruso001** [SpongeBobSun/mCalendarView#22]
Is there a way to clear all the points on a ExpCalendarView?

**Comment by SpongeBobSun** [comment]
Yep. Call `MarkedDates.emoveAdd` will clear all marked dates.

**Comment by SpongeBobSun** [comment]
@jcaruso001 BTW how was your app? Is it pulished yet?

**Comment by jcaruso001** [comment]
@SpongeBobSun I have not pushed it yet. I put it on the backlog while more profitable apps took priority. I'll let you know once it goes live.

**Comment by SpongeBobSun** [comment]
@jcaruso001 Haha, it's OK. Good luck with that!
