### ISSUE TITLE
markDates???

### ISSUE THREAD

**Issue by chengyixuan** [SpongeBobSun/mCalendarView#25]
when i want a caleendar hightlighting, If you don't switch a few times a month, have no effect 
, after thedrag ,  the date which you want  will hightlighting .   please!    why?   thanks!

**Comment by ShooterArk** [comment]
Did you find the solution I am still having this issue !!

**Comment by SpongeBobSun** [comment]
Fixed. Please pull the latest code.

**Comment by SpongeBobSun** [comment]
@chengyixuan @ShooterArk Ping....
