### ISSUE TITLE
The ExpCalendarView cannot be inside a fragment

### ISSUE THREAD

**Issue by wuxiao356** [SpongeBobSun/mCalendarView#26]
I am trying to use ExpCalendarView inside a Fragment. And there is a Navigation drawer to switch different fragments. The problem is, the ExpCalendarView will be loaded successfully at first time. But when I chose another fragment from navigation drawer and then switched back, the ExpCalendarView will disappear. That area for the calendar will be blank.

**Comment by SpongeBobSun** [comment]
Hmmm let me test it.

**Comment by wuxiao356** [comment]
Sorry, the library has no problem. It was something I did wrong.

**Comment by PascalAC** [comment]
@wuxiao356 How did you solve that problem? I'm facing the same issue right now.

**Comment by kaeul1020** [comment]
Please let me know how you solved the problem
