### ISSUE TITLE
ExpCalendarView travelTo() No effect

### ISSUE THREAD

**Issue by Samsu7609** [SpongeBobSun/mCalendarView#27]
代碼使用
Button click event -->  expCalendarView.travelTo(new DateData(2016 , 5, 5));

PS 假如是 MCalendarView.travelTo() 就可以移動
兩邊的travelTo 原碼是一樣的 init 的方法也是一樣的

**Comment by Samsu7609** [comment]
我想實現 click 後 move 到 指定的日期 並 highlight 
目前只能透過setOnDateClickListener 取得當前的 點擊 view
能提供一些思路嗎 謝謝

**Comment by SpongeBobSun** [comment]
Let me test it. Maybe this is a bug.

**Comment by mBigFlower** [comment]
OK, I find one way to do what you said, and I'll push a new version for you .

@SpongeBobSun  maybe we can use the jcenter for this widget, I think this is zhuangbility

**Comment by SpongeBobSun** [comment]
Fixed. Please pull the latest code @Samsu7609

**Comment by Samsu7609** [comment]
OK Thanks

**Comment by saddahussain** [comment]
Travel to does not work in shrink mode
