### ISSUE TITLE
Select on marked date

### ISSUE THREAD

**Issue by talazoft** [SpongeBobSun/mCalendarView#32]
Hello @SpongeBobSun 

It seems that I cant make selection on marked date, can you give me solution?

**Comment by htooaunghlaing** [comment]
Oh, you can mark selection for that,
 public void onDateClick(View view, DateData date) {
     Log.i("MARKED DATE", date.getDayString() + "-" + date.getMonthString() + "-" + date.getYear() + "");
     //mark the date
     calendarView.markDate(date);  
}

**Comment by SpongeBobSun** [comment]
@htooaunghlaing Thanks.

@talazoft Close this issue for now. Any further questions please re-open it.
