### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by jcaruso001** [SpongeBobSun/mCalendarView#33]
Can you put the build compile on the homepage so I don't have to look up if theres a new build it's just there on the read me.

compile 'com.github.SpongeBobSun:mCalendarView:6c384cdc8b'

**Comment by jcaruso001** [comment]
@SpongeBobSun  Can you put the compile command on the read me?

**Comment by SpongeBobSun** [comment]
Yep.

Maybe I'll upload it to jcenter tomorrow.

Get Outlook for iOShttps://aka.ms/o0ukef

On Sat, Nov 12, 2016 at 11:43 PM +0800, "Jason H Caruso" <notifications@github.com<mailto:notifications@github.com>> wrote:

@SpongeBobSunhttps://github.com/SpongeBobSun Can you put the compile command on the read me?

##

**Comment by jcaruso001** [comment]
@SpongeBobSun Was just not looking to see if you had an upgrade out and the compile command wasn't on the read me :-1:

**Comment by SpongeBobSun** [comment]
Added.
Waiting for jcenter review. 

Will update readme when approved.

**Comment by SpongeBobSun** [comment]
Done.

Come on dude! It's CNY and everybody take long vacations in China !
