### ISSUE TITLE
Expanded Calendar View

### ISSUE THREAD

**Issue by jcaruso001** [SpongeBobSun/mCalendarView#34]
I am adding points as the calendar scrolls to another month. However, the calendar doesn't refresh and show those new points unless it's closed an open again. Is there a way around this?

**Comment by SpongeBobSun** [comment]
@mBigFlower 
Please help to verify. 
I think it's just missing a refresh call, right ?

**Comment by jcaruso001** [comment]
Yes

**Comment by jcaruso001** [comment]
@mBigFlower Is there a method that will refresh it?

@SpongeBobSun I know you've asked before but my hope is to push this to beta next week.

**Comment by jcaruso001** [comment]
refreshDrawableState() ?

**Comment by SpongeBobSun** [comment]
Hmm let me check. Seems like my buddy is taking a rest.

Get Outlook for iOShttps://aka.ms/o0ukef

On Sat, Nov 12, 2016 at 11:25 PM +0800, "Jason H Caruso" <notifications@github.com<mailto:notifications@github.com>> wrote:

refreshDrawableState() ?

**Comment by SpongeBobSun** [comment]
@jcaruso001

Have you tried `MarkedDates.notifyObservers()` ? As I recall we've registered our adapters as observers.

**Comment by jcaruso001** [comment]
@SpongeBobSThat appears to have done it I'll test more to verify.

**Comment by jcaruso001** [comment]
@SpongeBobSun  We're [live](https://play.google.com/store/apps/details?id=com.projectcaruso.naturalfamilyplaning&hl=en)!

**Comment by SpongeBobSun** [comment]
@jcaruso001 WOW, Congrats!
