### ISSUE TITLE
ExpCalendarView can't select markDate ?

### ISSUE THREAD

**Issue by svran** [SpongeBobSun/mCalendarView#36]
![err2](https://cloud.githubusercontent.com/assets/13031351/20999572/79a2dec8-bd50-11e6-8d31-9dcd57a6588b.gif)

**Comment by SpongeBobSun** [comment]
@mBigFlower I think this is a feature not a bug, right?

**Comment by mBigFlower** [comment]
Thank you for the .gif, which is so clear .
We don't do anything for the marked Date. So you can edit it according to your idea.
Please see the  **[OnExpDateClickListener.class](https://github.com/SpongeBobSun/mCalendarView/blob/6c384cdc8b43ed1a4a38a343e903aa443c8c63a4/mcalendarview/src/main/java/sun/bob/mcalendarview/listeners/OnExpDateClickListener.java)**

For example:

![image](https://cloud.githubusercontent.com/assets/11960705/21003086/5a054344-bd64-11e6-8d39-9525772274db.png)

**Comment by svran** [comment]
Okay, thanks!
