### ISSUE TITLE
你这个截屏略搓啊

### ISSUE THREAD

**Issue by mBigFlower** [SpongeBobSun/mCalendarView#4]
kuan哥， 我有个截屏的，感脚不错，有需求不

**Comment by SpongeBobSun** [comment]
好久没弄这些了，，。。你可以fork一下帮我更新下截图，，，木哈哈

来自 魅族 MX4 Pro

-------- 原始邮件 --------
发件人：mBigMing notifications@github.com
时间：周三 9月23日 09:52
收件人：SpongeBobSun/mCalendarView mCalendarView@noreply.github.com
主题：[mCalendarView] 你这个截屏略搓啊 (#4)

> null

**Comment by mBigFlower** [comment]
fork了就可以在你的基础上改了是么？

**Comment by SpongeBobSun** [comment]
是的

来自 魅族 MX4 Pro

-------- 原始邮件 --------
发件人：mBigMing notifications@github.com
时间：周三 9月23日 10:35
收件人：SpongeBobSun/mCalendarView mCalendarView@noreply.github.com
抄送："bob.sun" widekuan@outlook.com
主题：Re: [mCalendarView] 你这个截屏略搓啊 (#4)

> null
