### ISSUE TITLE
MarkStyle.BACKGROUND Color

### ISSUE THREAD

**Issue by jcaruso001** [SpongeBobSun/mCalendarView#5]
Can you have different colors per day, instead of all blue like you have in the demo?

**Comment by SpongeBobSun** [comment]
Currently you can only set one mark color.
I will consider add `different color per day` to this widget.
Once it's done, I'll let you know.
Thanks.

**Comment by SpongeBobSun** [comment]
Hi, I've fixed this issue. Please pull the latest code.
Now you can use different highlight style & color between highlighted dates.
