### ISSUE TITLE
Please release new version

### ISSUE THREAD

**Issue by programmatix** [SpongeBobSun/mCalendarView#64]
I'm getting a crash inside MonthFragment when I rotate the screen.  I see the fragment is recreated and tries to access monthData which is now null.  I see you've already fixed this issue as the current version of the code checks monthData != null.  Could you please publish a new version with this fix?

**Comment by SpongeBobSun** [comment]
@programmatix 
Try 1.1.1 please.
```groovy
compile 'sun.bob:mcalendarview:1.1.1'
```
Thanks

**Comment by SpongeBobSun** [comment]
Closing this issue for now, ping me if you still have issue.

Thanks.
