### ISSUE TITLE
Un able to set DateCellView  on Calender View.

### ISSUE THREAD

**Issue by rahulkushwaha-dev** [SpongeBobSun/mCalendarView#65]
I am getting the issues while customising the date cell view in my app.
Issues  is  given as follows:-
     Binary XML file line #2: Binary XML file line #2: Error inflating class sun.bob.mcalendarviewtest.DateCellView
    Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class sun.bob.mcalendarviewtest.DateCellView
    Caused by: java.lang.ClassNotFoundException: Didn't find class "sun.bob.mcalendarviewtest.DateCellView" on path: DexPathList[[zip file "/data/app/com.example.lappy.calender-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.lappy.calender-1/lib/arm64, /system/lib64, /vendor/lib64]]

**Comment by Magderidon** [comment]
Its normal your project can't inflate a view that does not exist. 
In the documentation he used this.

<?xml version="1.0" encoding="utf-8"?>
  <sun.bob.mcalendarviewtest.DateCellView 
  	xmlns:android="http://schemas.android.com/apk/res/android"
      android:orientation="vertical"
      android:layout_width="100dp"
      android:layout_height="100dp"
      android:background="#00ADA3">
      <TextView
          android:layout_width="match_parent"
          android:layout_height="match_parent"
          android:textColor="#FFFFFF"
          android:id="@+id/id_cell_text"/>
  </sun.bob.mcalendarviewtest.DateCellView>

But in your project you need to use the name of your package.

<?xml version="1.0" encoding="utf-8"?>
<my.package.xxx.DateCellView 
  	. . .
 </my.package.xxx.DateCellView>

**Comment by rahulkushwaha-dev** [comment]
OK i resolved it succesfully.Thanks@ Magderidon
