### ISSUE TITLE
How to dynamically add markDate？

### ISSUE THREAD

**Issue by fg2q1q3q** [SpongeBobSun/mCalendarView#7]
Hello, my app  need to mark  date is more, so I plan to make a single month (when  sliding into this month) to dynamically increase the marking date, how to  notify the view?

my code for example,but the current view can't refresh
calendarView.setOnMonthChangeListener(new OnMonthChangeListener() {
            @Override
            public void onMonthChange(int year, int month,int position) {
                //改变标题栏
                getActivity().setTitle(year + "  " + month + "月");
                               //模拟标记数据
                calendarView.markDate(year, month,month/2+7);
                calendarView.markDate(year, month,month/2+13);
                calendarView.markDate(year, month,month/2+20);
            }
        }

**Comment by SpongeBobSun** [comment]
Ok, I have to say this is a big problem of this lib and I'm thinking of re-write those parts. 
I can provide a temporary work around to you but I'm not sure it fits your requirement or not.
To dynamically add mark-ups when month changing, you may not only need to add this month's date but also next month's date.

``` java
calendarView.setOnMonthChangeListener(new OnMonthChangeListener() {
@Override
public void onMonthChange(int year, int month,int position) {
//改变标题栏
getActivity().setTitle(year + " " + month + "月");
//模拟标记数据 - for this month
calendarView.markDate(year, month,month/2+7);
calendarView.markDate(year, month,month/2+13);
calendarView.markDate(year, month,month/2+20);
//add next mark data as well
month += 1; //Actually, increase by one may not safe -> 12 + 1 = 13
calendarView.markDate(year, month,month/2+7);
calendarView.markDate(year, month,month/2+13);
calendarView.markDate(year, month,month/2+20);
}
}
```

I'll re-write this part and when I'm done I'll let you know.

Thanks for the issue, you guys rock!

Bob.

**Comment by SpongeBobSun** [comment]
Ok I fixed this issue. 
Code will be updated tomorrow.

**Comment by SpongeBobSun** [comment]
Code updated. Please check.

**Comment by fg2q1q3q** [comment]
ok。thanks

**Comment by fg2q1q3q** [comment]
It is true that, although there is a little bit of not smooth, I know you have used the observation  mode to solve this problem, but I have a question, yesterday, I  added a param postion in onMonthChange , and then          use this position  through getItem to get Monthfragment instance, and then call adapter's notify method to refresh inside the Monthfragment instance, but print the adapter's value is null, why?

**Comment by SpongeBobSun** [comment]
Ok, that's because you can not get fragment instance by invoking ViewPager's adapter's getItem directly.  It is true that this method will return a `MonthFragment` but this fragment is not the one that already displayed on screen. So I use observation pattern to get MonthFragment updated. The performance issue can not be avoid when sliding & adding new marked dates. Anyway, I'm still thinking a better solution. If I got something I'll reply this issue to let you know. If you have any ideas, a pull request is welcome.
Thanks.
Bob.

**Comment by fg2q1q3q** [comment]
Thank you, perhaps, as you said at the beginning, the pre loading of last month and next month's data experience will be better, because my date of these markdatas is obtained from the server, so only dynamic load.
